_wandb:
    value:
        cli_version: 0.21.0
        e:
            9agmmligrqwoi7cz1tkzsg824lr5yv9i:
                codePath: assignment2\wnb\train_wandb.py
                codePathLocal: train_wandb.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "248200032256"
                        used: "221403361280"
                email: snehalyelwande07@gmail.com
                executable: C:\Users\hp\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 2ec3fbda63468b23ee73b95fe25878b99381722c
                    remote: https://github.com/SnehalLY/MLOPS_Assignments.git
                host: Snehal
                memory:
                    total: "16368844800"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\hp\OneDrive\Desktop\Mlops\assignment2\wnb\train_wandb.py
                python: CPython 3.12.1
                root: C:\Users\hp\OneDrive\Desktop\Mlops\assignment2\wnb
                startedAt: "2025-09-17T05:02:45.725818Z"
                writerId: 9agmmligrqwoi7cz1tkzsg824lr5yv9i
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 19
            "4": 3.12.1
            "5": 0.21.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.0
            "13": windows-amd64
max_depth:
    value: 5
n_estimators:
    value: 100
